name: rev_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  device_info_plus: ^10.1.0
  dio: ^5.3.2
  logger: ^2.0.2+1
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  razorpay_flutter: ^1.4.0
  path: ^1.8.3
  flutter_pdfview: ^1.3.2
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/images/cities/
    - assets/images/banners/
    - assets/images/bikes/
